version: 2
registries:
  maven-google:
    type: maven-repository
    url: https://maven.google.com
    username: ""
    password: ""
  maven-central:
    type: maven-repository
    url: https://repo1.maven.org/maven2
    username: ""
    password: ""
updates:
- package-ecosystem: gradle
  directory: "/01_firstapp"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/02_resources"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/03_constraintlayout"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/04_events"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/05_mvvm"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/06_recyclerview/diffutils"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/06_recyclerview/manual"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/06_recyclerview/recyclerview"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/07_crud"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/08_material"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/09_navigation"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/10_storage"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/11_fragments"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/12_sql"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/13_room"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/14_pushes"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
- package-ecosystem: gradle
  directory: "/push-sender"
  registries:
      - maven-google
      - maven-central
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  assignees:
  - amostyaev
